# .github/workflows/build-release.yml

name: Build and Release Package

# Step 1: Changed the trigger to run only on tag pushes
on:
  push:
    tags:
      - 'v*' # For example: v1.0, v2.3, etc.

jobs:
  build:
    runs-on: ubuntu-22.04
    # Step 2: Removed the build matrix and set the architecture directly
    env:
      PKG_NAME: cli11
      PROJECT_PATH: my-project-repo
      XBPS_TARGET_ARCH: x86_64

    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h .

      - name: Checkout your project repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.PROJECT_PATH }}

      - name: Checkout void-packages and xbps
        uses: actions/checkout@v4
        with:
          repository: void-linux/void-packages
          path: void-packages
      - name: Checkout xbps
        uses: actions/checkout@v4
        with:
          repository: void-linux/xbps
          ref: 0.60.5
          path: xbps

      - name: Build and install xbps
        run: |
          sudo apt-get update -y && sudo apt-get install -y libarchive-dev
          cd xbps
          ./configure --enable-rpath --prefix=/opt/xbps/usr
          make -j$(nproc)
          sudo make install clean
          export PATH="/opt/xbps/usr/bin/:$PATH"
          xbps-install --version

      - name: Copy package template
        run: cp -rv ${{ env.PROJECT_PATH }}/srcpkgs/${{ env.PKG_NAME }} void-packages/srcpkgs

      - name: Build package
        run: |
          export PATH="/opt/xbps/usr/bin/:$PATH"
          cd void-packages
          ./xbps-src -m masterdir-${{ env.XBPS_TARGET_ARCH }} -A ${{ env.XBPS_TARGET_ARCH }} binary-bootstrap
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ env.XBPS_TARGET_ARCH }} ${{ env.PKG_NAME }}

      - name: Create repository index
        working-directory: void-packages/hostdir/binpkgs/
        run: |
          export PATH="/opt/xbps/usr/bin/:$PATH"
          xbps-rindex -a ./*.xbps
          sha256sum *.xbps > sha256sum.txt

      # This step will now succeed because the workflow is triggered by a tag
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            void-packages/hostdir/binpkgs/cli11*
            void-packages/hostdir/binpkgs/*repodata
            void-packages/hostdir/binpkgs/sha256sum.txt
