# .github/workflows/build-artifact.yml

name: Build Package Artifact

# This workflow can now be run manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-22.04
    env:
      PKG_NAME: cli11
      PROJECT_PATH: my-project-repo
      XBPS_TARGET_ARCH: x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build your package
        run: echo "Building package ${{ env.PKG_NAME }}..." # Replace with your actual full build commands

      - name: Prepare package files for upload
        run: |
          # This is an example, replace with your actual file preparation
          mkdir -p void-packages/hostdir/binpkgs
          touch void-packages/hostdir/binpkgs/cli11-1.0_1.x86_64.xbps

      # This step replaces the "Create GitHub Release" step
      - name: Upload .xbps Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          # This will be the name of the downloadable file
          name: xbps-package-${{ env.PKG_NAME }}
          # This is the path to the file you want to upload
          path: void-packages/hostdir/binpkgs/*.xbps
