# .github/workflows/release.yml

name: Create Release

# This section is changed to trigger ONLY on tag pushes
on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0, v1.1.2, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    env:
      PKG_NAME: cli11
      PROJECT_PATH: my-project-repo
      XBPS_TARGET_ARCH: x86_64

    steps:
      # ... (Your existing build steps go here) ...
      
      # Example build steps - ensure your steps are here
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build your package
        run: echo "Building package ${{ env.PKG_NAME }}..." # Replace with your actual build commands
      
      - name: Prepare release files
        run: |
          # This is an example, replace with your actual file preparation
          mkdir -p void-packages/hostdir/binpkgs
          touch void-packages/hostdir/binpkgs/cli11-1.0_1.x86_64.xbps
          touch void-packages/hostdir/binpkgs/repodata
          touch void-packages/hostdir/binpkgs/sha256sum.txt

      # This step will now succeed because a tag exists
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            void-packages/hostdir/binpkgs/cli11*
            void-packages/hostdir/binpkgs/*repodata
            void-packages/hostdir/binpkgs/sha256sum.txt
